[project]
name = "nixpkgs-update-github-releases"
dynamic = ["version"]

[project.scripts]
nixpkgs-update-github-releases = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "env"
variable = "version"

[tool.hatch.build.targets.wheel]
only-include = ["main.py", "loadMetaFromPath.nix"]

[tool.ruff.lint]
select = ["I"] # TODO: run more lints
